---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: Webtop_mirmanda
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBFOLDER=/ 
      - KEYBOARD=es-es-qwerty
      - TITLE=Webtop_mirmanda
    volumes:
      - /path/to/data:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb" 
    restart: unless-stopped